{
 "title": "Router Stats",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "column": "usr",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_cpu",
     "query": "select mean(usr) from \"router_cpu\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "usr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "usr" ], "type": "alias" }
      ],
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "sys" ], "type": "alias" }
      ],
      [
       { "params": [ "sirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "sirq" ], "type": "alias" }
      ],
      [
       { "params": [ "irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "irq" ], "type": "alias" }
      ],
      [
       { "params": [ "nic" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "nic" ], "type": "alias" }
      ],
      [
       { "params": [ "io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "io" ], "type": "alias" }
      ]
     ],
     "series": "router_cpu"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "column": "used_kb",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_mem",
     "query": "select mean(used_kb) from \"router_mem\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "buffcache_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "buffer/cached" ], "type": "alias" }
      ],
      [
       { "params": [ "used_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "free_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ],
     "series": "router_mem"
    },
    {}
   ]
  },
  {
   "title": "Processor  Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_proc",
     "column": "recv_mbps",
     "function": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "proc" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "groupby_field": "interface",
     "measurement": "router_top_cpu",
     "query": "select interface, min(recv_mbps) from \"router_net\" where $timeFilter group by time($interval), interface order asc",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_net"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_proc",
     "column": "recv_mbps",
     "function": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "proc" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "groupby_field": "interface",
     "measurement": "router_top",
     "query": "select interface, min(recv_mbps) from \"router_net\" where $timeFilter group by time($interval), interface order asc",
     "select": [
      [
       { "params": [ "kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_net"
    }
   ]
  },
  {
   "title": "Wireless Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Clients",
     "column": "count",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_assoclist",
     "query": "select mean(count) from \"router_assoclist_24\" where $timeFilter group by time($interval) order asc",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_assoclist_24"
    }
   ]
  },
  {
   "title": "Current Clients",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "router_clients",
     "query": "SELECT \"ip\", \"mac\", \"name\" FROM \"router_clients\" WHERE $timeFilter \n",
     "select": [
      [
       { "params": [ "mac" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "External Ping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_dst",
     "column": "ms",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dst" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "groupby_field": "dst",
     "measurement": "router_ping_ext",
     "query": "select dst, mean(ms) from \"router_ping_ext\" where $timeFilter group by time($interval), dst order asc",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "router_ping_ext"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none", "label": "mbps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface",
     "column": "recv_mbps",
     "function": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "groupby_field": "interface",
     "measurement": "router_net",
     "query": "select interface, min(recv_mbps) from \"router_net\" where $timeFilter group by time($interval), interface order asc",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "series": "router_net"
    }
   ]
  },
  {
   "title": "Disk Used Space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_disk - $col",
     "column": "used_kb",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router_df",
     "query": "SELECT mean(\"used\") / (mean(\"available\") + mean(\"used\")) AS \"used\" FROM \"router_df\" WHERE $timeFilter GROUP BY time($__interval), \"disk\" fill(null)",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+ used" ], "type": "math" },
       { "params": [ "free" ], "type": "alias" }
      ]
     ],
     "series": "router_mem"
    }
   ]
  }
 ]
}